"""The seeded demo codebase, served by GET /rooms/{id}/files[/{path}].

Mirrors web/lib/workspace.ts's `workspaceFiles` (paths and starting content)
so the same demo repo looks identical whether a viewer is watching the
fixture player or a live room. Content written during execution is
generated by app/k2/execution.py, not hand-authored here — this module only
holds the *before* state.

Kept as a plain Python literal, same reasoning as web/lib/workspace.ts: no
real git checkout for the MVP, and CLAUDE.md's workspace-seed concept
("Set once. Never hand-edited after.") is satisfied by treating this list
itself as the seed.
"""

from __future__ import annotations

SEED_FILES: dict[str, str] = {
    "README.md": """# ledger-api

Small expense-tracking API. Currently unauthenticated: every route is public
and `current_user` is hard-coded to the seed user.

## Layout

- `src/app.py` — routes
- `src/auth/` — authentication (empty; this is the work)
- `src/models/user.py` — the User record
- `tests/` — pytest

## Running

    pip install -r requirements.txt
    uvicorn src.app:app --reload
""",
    "requirements.txt": """fastapi==0.115.0
uvicorn==0.30.6
pydantic==2.9.2
pytest==8.3.3
""",
    "src/app.py": '''from fastapi import FastAPI

from src.models.user import SEED_USER, User

app = FastAPI(title="ledger-api")

_EXPENSES: list[dict] = []


def current_user() -> User:
    # TODO: no authentication yet. Everything runs as the seed user.
    return SEED_USER


@app.get("/expenses")
def list_expenses() -> list[dict]:
    user = current_user()
    return [e for e in _EXPENSES if e["user_id"] == user.id]


@app.post("/expenses")
def create_expense(amount_cents: int, memo: str) -> dict:
    user = current_user()
    expense = {"user_id": user.id, "amount_cents": amount_cents, "memo": memo}
    _EXPENSES.append(expense)
    return expense
''',
    "src/auth/__init__.py": "",
    "src/auth/session.py": '"""Session helpers. Not written yet — ticket t1 (a1)."""\n',
    "src/auth/jwt.py": '"""JWT helpers. Not written yet — ticket t2 (a2)."""\n',
    "src/auth/middleware.py": '"""authenticate_user dispatcher. Not written yet — ticket t3 (a1)."""\n',
    "src/models/user.py": '''from dataclasses import dataclass


@dataclass(frozen=True)
class User:
    id: str
    email: str
    password_hash: str


SEED_USER = User(id="u_seed", email="dev@example.com", password_hash="!")

_USERS: dict[str, User] = {SEED_USER.id: SEED_USER}


def find_user(user_id: str) -> User | None:
    return _USERS.get(user_id)


def find_user_by_email(email: str) -> User | None:
    return next((u for u in _USERS.values() if u.email == email), None)
''',
    "tests/test_auth.py": '''import pytest

pytestmark = pytest.mark.skip(reason="no authentication yet — ticket t4 (a2)")


def test_login_sets_cookie_and_returns_token():
    ...
''',
}


def seed_files() -> dict[str, str]:
    return dict(SEED_FILES)


def file_tree(paths: list[str]) -> list[dict]:
    """Nested {type, name, path, children?} tree — same shape as
    web/lib/workspace.ts's buildTree, for GET /rooms/{id}/files."""
    root: list[dict] = []

    for path in sorted(paths):
        segments = path.split("/")
        level = root
        for i, name in enumerate(segments):
            here = "/".join(segments[: i + 1])
            is_leaf = i == len(segments) - 1
            if is_leaf:
                level.append({"type": "file", "name": name, "path": here})
                continue
            existing = next(
                (n for n in level if n["type"] == "dir" and n["name"] == name), None
            )
            if existing is None:
                existing = {"type": "dir", "name": name, "path": here, "children": []}
                level.append(existing)
            level = existing["children"]

    def sort_tree(nodes: list[dict]) -> list[dict]:
        for n in nodes:
            if n["type"] == "dir":
                sort_tree(n["children"])
        nodes.sort(key=lambda n: (n["type"] != "dir", n["name"]))
        return nodes

    return sort_tree(root)
